name: E2E Inaccessible Workflows (Should fail!) 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-tests]
  
jobs:
  inaccessible:
    uses: immutable-actions/e2e-test-consumer-public/.github/workflows/consume-inaccessible-actions.yml@main
