name: E2E Packages References internal fail (Should fail!) 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-tests]
  
jobs:  
  consume-package-actions:
    uses: immutable-actions/e2e-test-consumer-public/.github/workflows/consume-package-actions.yml@main
